name: coqui-blabber

channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - setuptools<75
  - wheel
  - cython
  - cmake
  - ninja
  - pkg-config
  - libsndfile
  - ffmpeg
  - numpy<2
  - scipy<1.14

  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu121
      - setuptools-scm
      - soundfile>=0.12,<0.14

      # CUDA Torch stack, compatible with many CUDA 12.x drivers
      - torch==2.4.1
      - torchaudio==2.4.1
      - torchvision==0.19.1

      - coqui-tts==0.27.5
      - gruut
      - youtokentome==1.0.6
      - nemo_toolkit[tts]==1.23.0

      # must satisfy Coqui
      - transformers>=4.57,<4.58

      - pytorch-lightning==2.0.7
      - git+https://github.com/apple/ml-acn-embed@main
